volumes:
  go-bin:
  go-pkg:

services:
  postgresql:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: 'devel'
      POSTGRES_PASSWORD: 'devel'
      POSTGRES_DB: 'devel'
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready

  smtp-mock:
    image: 'local/smtp-mock'
    build:
      context: smtp-mock
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - nc -z -v localhost 2024

  server:
    image: 'local/asl-bissieux'
    build:
      context: .
      target: server-devel
    command:
      - server
      - -v
    working_dir: /go/src/github.com/rclsilver/asl-bissieux
    volumes:
      - go-bin:/go/bin
      - go-pkg:/go/pkg
      - ${PWD}:/go/src/github.com/rclsilver/asl-bissieux
    ports:
      - 8080
    depends_on:
      postgresql:
        condition: service_healthy
      smtp-mock:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - curl --fail -k http://localhost:8080/api/mon/ping

  frontend:
    depends_on:
      server:
        condition: service_healthy
    image: local/asl-bissieux-frontend
    build:
      context: .
      target: frontend-devel
    volumes:
    - ./frontend:/app
    working_dir: /app
    command: su node -c 'npm install && npm install --only=dev && npm start'
    ports:
      - 4200

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      URL: http://localhost:8080/api/spec.json
    ports:
      - 8080
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - curl --fail -k http://localhost:8080
